### ISSUE TITLE
Redesign https://ipfs.io/blog/

### ISSUE THREAD

**Issue by em-ly** [ipfs/blog#60] opened 2016-06-30 17:41 UTC
Instead of listing the links to the blogs, can we feature the most recent blog post? This page/portal could use a lot of love. What do you think @RichardLitt?

**Comment by RichardLitt** [comment] 2016-06-30 18:19
That sounds smart to me.

**Comment by em-ly** [comment] 2016-07-01 06:21
@RichardLitt Glad you agree! What do the next steps for that look like? Who owns the design of this page? Can we move to a Wordpress model? If not, what are our options?

**Comment by RichardLitt** [comment] 2016-07-01 09:30
- Next steps: Feedback from @jbenet. I don't like making design decisions without his feedback. 
- Design owner: @jbenet.
- Wordpress: negative. We should keep this using IPFS, so that it is permanent. 
- Options: AFAIK, keep the current system, just redesign it. The website was recently redone, but the blog wasn't included. 

However, an overhaul in general shouldn't be talked about here: it's a duplicate of [this issue](https://github.com/ipfs/website/issues/131) posted by @jbenet a bit ago.

**Comment by lgierth** [comment] 2016-07-03 00:39
> Wordpress: negative. We should keep this using IPFS, so that it is permanent. 

Agreed, it's also important that we eat our own dogfeed as much as possible, just to demonstrate that it works, the different use cases, etc.

**Comment by dignifiedquire** [comment] 2016-07-03 08:24
In the previews for the website there was already a new design for the blog done by &yet, what happened to that?

**Comment by diasdavid** [comment] 2016-07-03 09:03
@em-ly I believe what you mean by a `moving to a Wordpress model` is more in the lines of getting a nicer experience to publish and track the activity on each blog post, than using Wordpress itself. The reason why we are reluctant to move to Wordpress is because of how it is set up, Wordpress is a full Web Service, with a DB, a Web Server and currently, there is no way to serve a blog out of Wordpress through IPFS (yet! :)).

We can always level up our blog to have a nicer editing experience and a monitoring one (Google Analytics, twitter cards, Open Graph, whatever, you name it :))

**Comment by mishmosh** [comment] 2017-05-25 20:04
Per #101 we will not change blog design until higher volume of posts or activity warrants it.

**Closed by mishmosh** 2017-05-25 20:04 UTC
Labels: meta
